### ISSUE TITLE
Does not play music

### ISSUE THREAD

**Issue by MrGhostOff** [H5Pro2/Kyoko-Musicbot#1]
Constantly writes that the URL is incomplete. How to fix? URL normal and complete.

**Comment by H5Pro2** [comment]
I will look for it. generally writes the bot this message only if an error in the url is present.

 

-------------------------------------------------

 

incomplete path etc.

start with ("https://www.youtube.com")
should mean that the bot only youtube url accepts

 

-------------------------------------------------

 

/bot_module/music_play_modul.js 

 

ytdl.getInfo (url = String (url), (error, videoInfo) =>{
if (error) {
    return message.channel.send (wrap ("Error incomplete url")); // (( URL is incomplete ))
}

if ytdl recognizes that the URL is incomplete, this will give an error.
is for protection that the bot does not hang up.

 

-------------------------------------------------

 

 


Gesendet: Dienstag, 07. August 2018 um 22:25 Uhr
Von: MrGhostOff <notifications@github.com>
An: H5Pro2/Kyoko-Musicbot <Kyoko-Musicbot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [H5Pro2/Kyoko-Musicbot] Does not play music (#1)


Constantly writes that the URL is incomplete. How to fix? IRL normal and complete.

**Comment by MrGhostOff** [comment]
![default](https://user-images.githubusercontent.com/33192257/45825429-e84ce700-bcfa-11e8-936f-bd80b80b97ef.png)

**Comment by MrGhostOff** [comment]
Is there a problem with the versions of module?

**Comment by MrGhostOff** [comment]
I decided to output the error via console.log (error);
`Error: No video id found: send(content, options) {
    if (!options && typeof content === 'object' && !(content instanceof Array)) {
      options = content;
      content = '';
    } else if (!options) {
      options = {};
    }

    if (options instanceof Attachment) options = { files: [options.file] };
    if (options instanceof RichEmbed) options = { embed: options };

    if (options.embed && options.embed.file) {
      if (options.files) options.files.push(options.embed.file);
      else options.files = [options.embed.file];
    }

    if (options.file) {
      if (options.files) options.files.push(options.file);
      else options.files = [options.file];
    }

    if (options.files) {
      for (let i = 0; i < options.files.length; i++) {
        let file = options.files[i];
        if (typeof file === 'string' || Buffer.isBuffer(file)) file = { attachment: file };
        if (!file.name) {
          if (typeof file.attachment === 'string') {
            file.name = path.basename(file.attachment);
          } else if (file.attachment && file.attachment.path) {
            file.name = path.basename(file.attachment.path);
          } else if (file instanceof Attachment) {
            file = { attachment: file.file, name: path.basename(file.file) || 'file.jpg' };
          } else {
            file.name = 'file.jpg';
          }
        } else if (file instanceof Attachment) {
          file = file.file;
        }
        options.files[i] = file;
      }

      return Promise.all(options.files.map(file =>
        this.client.resolver.resolveFile(file.attachment).then(resource => {
          file.file = resource;
          return file;
        })
      )).then(files => this.client.rest.methods.sendMessage(this, content, options, files));
    }

    return this.client.rest.methods.sendMessage(this, content, options);
  }
    at Object.exports.getURLVideoID (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ytdl-core\lib\util.js:257:12)
    at Object.exports.getVideoID (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ytdl-core\lib\util.js:279:20)
    at Function.getInfo (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ytdl-core\lib\info.js:46:17)
    at Object.exports.play_song (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\bot_module\music_play_modul.js:129:14)
    at Object.exports.run (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\bot_commands\set_playsong.js:32:13)
    at Client.<anonymous> (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\index.js:175:25)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at MessageCreateHandler.handle (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:189:7)
    at Receiver._receiver.onmessage (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\receiver.js:409:14)
    at Receiver.getData (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\receiver.js:347:12)
    at Receiver.startLoop (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\receiver.js:143:16)
    at Receiver.add (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\node_modules\ws\lib\receiver.js:117:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:189:7)`

**Comment by MrGhostOff** [comment]
I decided to output the error via console.log (error);
https://pastebin.com/eALe0LdE

**Comment by H5Pro2** [comment]
i test the Link.. it works fine.
+play https://www.youtube.com/watch?v=YwAS2L69EA0

ok you config a bot channel ??
under bot_setting.json
[ "botchannel"    : " " ]
for example.. botchannel or music-room

I have a bot channel with the name bot-eingabe for example .. 
Even if I told the bot he was assigned in another channel, it works.

**Comment by MrGhostOff** [comment]
He enters the channel and gives an error.

**Comment by H5Pro2** [comment]
i fix an error on the set-play command 

if (bot_MessChannel==null){return message.channel.send(wrap("bot channel not config"))}

and 

if(message.channel.name!=botchannel){
        message.delete();// lösche die gepostete url messages  
        return message.channel.send(wrap("please write in the bot channel"));}

is bot channel not config / then 
is... not write in bot channel / then

**Comment by H5Pro2** [comment]
if one of them hits, the bot does not enter the voice channel

**Comment by MrGhostOff** [comment]
Can you say the versions of the modules? Perhaps the problem is this.

**Comment by H5Pro2** [comment]
what I fixed is an error that occurs ... in discord.js / typings / index.d.ts

a problem with the send embed function.

because Message channel gets zero there is an error.

**Comment by H5Pro2** [comment]
The console.log output from you is a ytdl.getInfo problem. 

at Object.exports.play_song (C:\Users\MrGhost\Desktop\DiscordBots\Kyoko-Musicbot-master\bot_module\music_play_modul.js:129:14)

how I see it.

**Comment by MrGhostOff** [comment]
It works! Thank you!

**Comment by H5Pro2** [comment]
ah ok nice... as long as I can help no problem. ;)

**Comment by H5Pro2** [comment]
ok I've edited the manual again.

push the emoji in your server.
then you have admin command.
( prefix admin )

ok... these send you a list of admin commands.

now the image emoji id´s you have to enter in ( bot_images/player_emoji.json )

**Comment by H5Pro2** [comment]
actually, the file has since lost nothing and belongs more in the field as a setting ... I will change that.

**Comment by MrGhostOff** [comment]
![default](https://user-images.githubusercontent.com/33192257/45888323-704bf300-bdc6-11e8-9745-74f4fb2142ed.png)

**Comment by MrGhostOff** [comment]
Oh... Unfortunately, I don't know how to fix this. An error occurs when you enter +emojis

**Comment by H5Pro2** [comment]
sorry i was just out of the house.

So that's new to me. 

Are these the emoji I gave with you or did you upload your own?

**Comment by H5Pro2** [comment]
ah ok wait ... how many emoji did you upload to your server ????
because then everyone tries to list in an embed message.

this in turn can lead to an error.

1024 bytes (1kb) are equal to 1024 characters. [Look here](http://slideplayer.org/slide/1282976/3/images/7/Speichergr%C3%B6%C3%9Fen+Die+kleinste+Speichereinheit+ist+1+Bit.jpg)
If these are exceeded, this error occurs.

the problem with which I have always had a problem in node.js is this point with the memory size or variable size.

in an array, I can load a lot more sign.
the problem is due to a variable issue which has a limit.

Unfortunately, I am not a programmer to explain why.
or did I ever know why and forget it? no matter

**Comment by H5Pro2** [comment]
for example ... that [450661466287112204 =: kick1: | kick] are 35 characters.

35 characters * 35 emojs = 1050 sign = 1050 byte

but that varies +/-

**Comment by MrGhostOff** [comment]
The error was in the long name emoji
Can you still tell me how to use the +emoji command?

**Comment by H5Pro2** [comment]
if your prefix + for example,
than you write in the bot channel +emojis

have you already pulled the update?

**Comment by MrGhostOff** [comment]
Да, я обновил бота. То есть мне нужно просто написать +emojis и добавить эмоцию?

**Comment by MrGhostOff** [comment]
Yes, I updated the bot. So I just need to write + emojis and add emotion?

**Comment by MrGhostOff** [comment]
Don't you get bored of my stupid questions?

**Comment by H5Pro2** [comment]
ich versuch dir gerade zu folgen.

nein nein alles gut, ich will dir ja helfen.

mit +emoji zeigt der bot nur die id´s an, als [privat message.](https://cdn.discordapp.com/attachments/492756462595211284/492756521403547668/admin_emoji.png)

**Comment by H5Pro2** [comment]
the emoji add [here ](https://cdn.discordapp.com/attachments/492756462595211284/492757945503973410/Unbenannt.png)

server setting/add emoji

**Comment by MrGhostOff** [comment]
I entered the emoji command, but in response only such an error
![default](https://user-images.githubusercontent.com/33192257/45898332-620bd000-bde2-11e8-96c2-6877bfd8b0e5.png)
![default](https://user-images.githubusercontent.com/33192257/45898362-764fcd00-bde2-11e8-80c4-56f3752c813e.png)

**Comment by MrGhostOff** [comment]
Maybe all the same problem in different versions of discord-js?

**Comment by H5Pro2** [comment]
hm I have to take a closer look

**Comment by H5Pro2** [comment]
you start the bot and then comes the message ??

or the error comes only if you put the command

**Comment by MrGhostOff** [comment]
Only when entering a command

**Comment by H5Pro2** [comment]
ok, these are the only emoji on the server you added ??

**Comment by H5Pro2** [comment]
holy shit ^^ here is your problem I think

**Comment by MrGhostOff** [comment]
Great problem :)

**Comment by H5Pro2** [comment]
ok you have 47 emoji the bot send all the emoji id´s in 1 embed field.

look here bot_commands/admin_custom_emoji_id.js 

        const emojiList = message.guild.emojis.map((e, x) => (x + ' = ' + e) + ' | ' +e.name).join('\n');
        let embed = new discord.RichEmbed()
        .addField("Custom Emoji Liste :",emojiList )
        .setColor(RandomColor)
        .setTimestamp()
        message.author.send({embed: embed});

**Comment by H5Pro2** [comment]
So an emoji has 20 signs
then that's called 20 * 47 = 1410 sign that's oversize

**Comment by H5Pro2** [comment]
the one [emoji ](https://cdn.discordapp.com/attachments/492756462595211284/492766637234192384/Unbenadnnt.png) here already has 27 signs.

**Comment by MrGhostOff** [comment]
Stupid limitation

**Comment by H5Pro2** [comment]
Yes that's it

I could try the anderst to write and in the emoji id's in several embed messages list.

but that would take a while.

see for example in read_write_modul.js

get_song_at_list:

         var url_buffer = fs.readFileSync (song_path + auth_id + urlInput);
         var url = JSON.parse (url_buffer);

         var url_info_buffer = fs.readFileSync (song_list_path + auth_id + urlInfo)
         var url_info = JSON.parse (url_info_buffer);

         var songlength = url.length;
         var songlengthmsg = url.length-1;
         var getNumber = message.content.slice (slice);

**Comment by H5Pro2** [comment]
so i split the characters in 4 embed messages 
to get around the error

**Comment by H5Pro2** [comment]
lol I did not expect that someone has 45+ emojis in his list ^^

**Comment by MrGhostOff** [comment]
В итоге удалил все emoji xD
![default](https://user-images.githubusercontent.com/33192257/45900665-1a3c7700-bde9-11e8-937d-0bddbb11e635.png)
Thank you!

**Comment by H5Pro2** [comment]
ah ok it works fine ... I will not fix it anymore today ^^

**Comment by MrGhostOff** [comment]
Sorry for spending your day

**Comment by H5Pro2** [comment]
all good..
not really.

I cook on the side 
and play video game ^^

**Comment by MrGhostOff** [comment]
Good luck to you!

**Comment by H5Pro2** [comment]
for further problems just write.

**Comment by MrGhostOff** [comment]
I found a new error! xD
![default](https://user-images.githubusercontent.com/33192257/45915310-8bb50d80-be5b-11e8-80dc-095236a43c88.png)

**Comment by H5Pro2** [comment]
ok this is a random feature with some youtube url`s

var URLArray = [
     "FlmToFkw9W0"
     "LLB39g0ix1A"
     "3_-a9nVZYjk"
     "Mgfe5tIwOj0"
]

I have never had an error so far.

tell me what you did exactly that you got this.

**Comment by MrGhostOff** [comment]
I just wrote a command.
![default](https://user-images.githubusercontent.com/33192257/45915999-557d8b00-be67-11e8-9f72-146202f61dd4.png)

**Comment by H5Pro2** [comment]
???hm ok

if you go search you have to write behind it what you are looking for

if i just search in it comes automatically to me.
https://www.youtube.com/watch?v=FxQTY-W6GIo

**Comment by MrGhostOff** [comment]
If you enter what you are looking for, you will get the same error
![default](https://user-images.githubusercontent.com/33192257/45916118-54e5f400-be69-11e8-81f7-e1e2bf772cd8.png)

**Comment by H5Pro2** [comment]
if (!json.items[0])callback(URLArray[Math.floor(Math.random()* URLArray.length)]);
                           ^

TypeError: Cannot read property '0' of undefined
    at Request._callback (D:\Discord sachen\Discord-js.Programming\Kyoko-MusicBot - programm ordner\bot_module\music_play_modul.js:163:28)
    at Request.self.callback (D:\Discord sachen\Discord-js.Programming\Kyoko-MusicBot - programm ordner\node_modules\request\request.js:186:22)
--------------------------------------------------------------------
ok I found out where your problem lies.

you need a yt_api_key so a youtube api key.

if you have one but have entered fasch in the setting.
This error can also occur.

**Comment by H5Pro2** [comment]
`no problem`

I have the eaber just fixed that if you do not write anything behind a medung comes.

I'll fix that still he writes a message fals the api key is wrong or missing

**Comment by H5Pro2** [comment]
ok, I fixed that
I will upload that later.

But must now work in the garden something ^ ^

**Comment by H5Pro2** [comment]
ok i fix that.
if I do not send the message as embed there are no problems ... as I said this is a problem with the embed messages that can list only 1kb.

**Comment by H5Pro2** [comment]
but I'm glad if you find fault.

**Comment by H5Pro2** [comment]
(sorry for my English)

no thing i'm dyslexic myself ^^
--------------------------------------
ja das kenne ich. Deshalb fing ich an mir einen eigennen zu schreiben.

ich finde eben auch diesen manga style und die widergabe echt cool.

**Comment by H5Pro2** [comment]
I will also do that so that you can write all messages in a file itself.

So you can adapt that to your language

**Comment by MrGhostOff** [comment]
I will be grateful

**Comment by MrGhostOff** [comment]
Visual code studio accept "", for the error. Put in front of the dash //
![default](https://user-images.githubusercontent.com/33192257/45955436-9072f080-c018-11e8-83fd-0c9f130ee8e5.png)

**Comment by MrGhostOff** [comment]
That is, replace
"-------------------------------":"", 
on
//-------------------------------

**Comment by MrGhostOff** [comment]
Found a bug. If you stop the song and continue, then the player does not appear (Previously, this was not)
![default](https://user-images.githubusercontent.com/33192257/45956205-a41f5680-c01a-11e8-9370-2b3617dce67d.png)

**Comment by MrGhostOff** [comment]
Player appears only when playing the next song.

**Comment by H5Pro2** [comment]
Through the whole change some errors have occurred, but I have fixed so far again. The duplicate objects are not really relevant and usually do not cause any problems. I can still change that.

**Comment by MrGhostOff** [comment]
It is necessary to change the prefix of the command.
![default](https://user-images.githubusercontent.com/33192257/45975396-d2b62500-c04c-11e8-91d3-1a4392ef7710.png)

**Comment by H5Pro2** [comment]
was changed.

**Comment by MrGhostOff** [comment]
Unfortunately, I was busy studying and on my return I saw a lot of updates. To begin with, after the play command, the suche bot constantly writes purge

**Comment by H5Pro2** [comment]
sorry i had seen your message too late.

I have a new update upload.

As I have some new features installed, there were unfortunately some bugs, but I have fixed so far.

**Comment by MrGhostOff** [comment]
I saw your update and I don’t know if you were trying to fix the constant writing of the purge command. If anything, then when writing all the commands to clear everything is still written to infinity

**Comment by MrGhostOff** [comment]
Why would you do so that after the command the messages themselves are deleted, and the purge command is not written?

**Comment by H5Pro2** [comment]
ok I've seen that there are still problems.
I'll take a look.

**Comment by H5Pro2** [comment]
so ok ... that should work now.

I've installed a lock with the message that you can specify in the setting a minimum of 10 delete messages.

In addition, a new function to tell you if the bot should send the emoji bar with or not.

Furthermore, I have improved the response of the commands on the emojis and these are now directly addressed and no longer on the message channel, which was actually completely stupid ^ ^ but ok.

As I said I'm not a computer scientist and do it only as a hobby.

**Comment by MrGhostOff** [comment]
I understand that this is your hobby and you are not a programmer. The bottom line is that the error has remained and now the bot simply sends messages about deletion infinitely
![default](https://user-images.githubusercontent.com/33192257/46872099-ef6b9e80-ce3b-11e8-98e2-721e7b3725ca.png)

**Comment by MrGhostOff** [comment]
I do not fully understand your code, but you can also delete the command message using bot_MessChannel.bulkDelete (1). That is, the user will write a command, and the bot will only delete it, instead of 10

**Comment by H5Pro2** [comment]
ich könnte das so machen...

wenn zu viele messages im chat sind, nachdem der bot on geht,

also über [ message_size_delete ] löscht er den channel und schreibt einen neuen mit der [ botchannel  ] bezeichnung.

`if(messages.size > message_size_delete){
                    console.log("hallo")
                    message.channel.delete(bot_MessChannel)

                    setTimeout(function () {   
                        var server = message.guild;
                        var name = message.author.username;

                        server.createChannel(botchannel, "text")
                    }, 500);

                    return; 
                }`

**Comment by MrGhostOff** [comment]
Why should a bot make a new channel? Is it really impossible to make the system delete only the command, not the last 10 messages?

**Comment by H5Pro2** [comment]
I've designed the bot so that the channel is always clean.

this is the command (.bulkDelete).

ok this function can only delete a maximum of 100 messages. This is given in discord node.js.

Assuming the channel has more than 100 messages in the channel.
Then the bot deletes the first 100 messages but then the bot will tell, ok there are still messages in the channel so I delete them too.

The bot always writes message has been deleted.
Thus, this query triggers by itself.


There is also a problem with how old the messages are.
if they are more than 1 day old the command works
[message.delete ()] or (.bulkDelete) not and it comes to an error.

my thought was just that the bot when starting recognizes, ok there are too many messages in the channel or too old, so I delete the bot channel and and create a new one.

**Comment by MrGhostOff** [comment]
Ok, i understand you

**Comment by H5Pro2** [comment]
how many messages should he delete you can specify in the settings (message_size_delete).

**Comment by H5Pro2** [comment]
so far that works!

I can play the update later

**Comment by MrGhostOff** [comment]
The question is not quite on the topic, but do you use this [documentation](https://discord.js.org/#/docs/main/stable/general/welcome)?

**Comment by H5Pro2** [comment]
meinst du discord.js ??

**Comment by H5Pro2** [comment]
node.js is just the backbone.
but for the whole server function, etc., of course I need discord.js.

**Comment by H5Pro2** [comment]
ok I once created a npm install batch.

I hope that works too.
i tested this on my system and it worked fine.

There are a few mistakes in the whole changes but I will fix it in the course.

I try to make the bot spam safe, which is not easy.

for example, when you play and leave spamming.

**Comment by MrGhostOff** [comment]
In general, I asked about the documentation that you use, since the official is not very clear to me, but oh well. In the morning I will test the bot.

**Comment by MrGhostOff** [comment]
You do not know how to make a bot create a voice channel with the help of a command and with permissions for an individual? By the way, do you not want to do new things in the future or will kyoko be just a music bot?

**Comment by H5Pro2** [comment]
first kyoko is a musikbot, for now.
as long as the functions do not work as I would like,
I do not want to build too much.

The problem is also that I always come up with something new and I look how I can implement that.

So yes I use the documentation of discord.js, as far as possible.
Unfortunately, I have to read a lot, try and find solutions to set functions.
as a non-computer scientist not easy :(

create a voice channel with the help of an authority and a command ??.
would go, I just have to install.
if I understood correctly.

if you have suggestions about functions, I have not got anything. you just have to say what and how it should look like.
I do not mind if you write something yourself and want to contribute ..
